// Generated by tools/cmn2hpp.py. Aggregates every COMMON-block struct. DO NOT EDIT.
#ifndef X13_CONTEXT_HPP
#define X13_CONTEXT_HPP
#include "x13/x13error.hpp"
#include "x13/channels.hpp"
#include "x13/savestate.hpp"
#include "common/gen/adj_cmn.hpp"
#include "common/gen/adxser_cmn.hpp"
#include "common/gen/agr_cmn.hpp"
#include "common/gen/agrsrs_cmn.hpp"
#include "common/gen/arima_cmn.hpp"
#include "common/gen/autoq_cmn.hpp"
#include "common/gen/bstmdl_cmn.hpp"
#include "common/gen/chrt_cmn.hpp"
#include "common/gen/error_cmn.hpp"
#include "common/gen/extend_cmn.hpp"
#include "common/gen/filetb_cmn.hpp"
#include "common/gen/force_cmn.hpp"
#include "common/gen/fxreg_cmn.hpp"
#include "common/gen/getarg_cmn.hpp"
#include "common/gen/global_cmn.hpp"
#include "common/gen/goodob_cmn.hpp"
#include "common/gen/hiddn_cmn.hpp"
#include "common/gen/htmlfile_cmn.hpp"
#include "common/gen/htmlout_cmn.hpp"
#include "common/gen/inpt_cmn.hpp"
#include "common/gen/inpt2_cmn.hpp"
#include "common/gen/lkhd_cmn.hpp"
#include "common/gen/lzero_cmn.hpp"
#include "common/gen/mdldat_cmn.hpp"
#include "common/gen/mdldg_cmn.hpp"
#include "common/gen/metadata_cmn.hpp"
#include "common/gen/missng_cmn.hpp"
#include "common/gen/model_cmn.hpp"
#include "common/gen/mq3_cmn.hpp"
#include "common/gen/newmdl_cmn.hpp"
#include "common/gen/orisrs_cmn.hpp"
#include "common/gen/otlrev_cmn.hpp"
#include "common/gen/otxrev_cmn.hpp"
#include "common/gen/picktd_cmn.hpp"
#include "common/gen/priadj_cmn.hpp"
#include "common/gen/prior_cmn.hpp"
#include "common/gen/prittl_cmn.hpp"
#include "common/gen/priusr_cmn.hpp"
#include "common/gen/rev_cmn.hpp"
#include "common/gen/revsrs_cmn.hpp"
#include "common/gen/revtrg_cmn.hpp"
#include "common/gen/revusr_cmn.hpp"
#include "common/gen/rho_cmn.hpp"
#include "common/gen/savcmn_cmn.hpp"
#include "common/gen/seatad_cmn.hpp"
#include "common/gen/seatcm_cmn.hpp"
#include "common/gen/seatdg_cmn.hpp"
#include "common/gen/seatlg_cmn.hpp"
#include "common/gen/seatmd_cmn.hpp"
#include "common/gen/seatop_cmn.hpp"
#include "common/gen/series_cmn.hpp"
#include "common/gen/spcidx_cmn.hpp"
#include "common/gen/ss2rv_cmn.hpp"
#include "common/gen/ssap_cmn.hpp"
#include "common/gen/ssft_cmn.hpp"
#include "common/gen/sspdat_cmn.hpp"
#include "common/gen/sspinp_cmn.hpp"
#include "common/gen/ssprep_cmn.hpp"
#include "common/gen/sspvec_cmn.hpp"
#include "common/gen/stcfcm_cmn.hpp"
#include "common/gen/svllog_cmn.hpp"
#include "common/gen/tbllog_cmn.hpp"
#include "common/gen/tdtyp_cmn.hpp"
#include "common/gen/tests_cmn.hpp"
#include "common/gen/tfmts_cmn.hpp"
#include "common/gen/title_cmn.hpp"
#include "common/gen/tukey_cmn.hpp"
#include "common/gen/units_cmn.hpp"
#include "common/gen/urgbak_cmn.hpp"
#include "common/gen/usrreg_cmn.hpp"
#include "common/gen/usrxrg_cmn.hpp"
#include "common/gen/work2_cmn.hpp"
#include "common/gen/x11adj_cmn.hpp"
#include "common/gen/x11fac_cmn.hpp"
#include "common/gen/x11log_cmn.hpp"
#include "common/gen/x11msc_cmn.hpp"
#include "common/gen/x11opt_cmn.hpp"
#include "common/gen/x11ptr_cmn.hpp"
#include "common/gen/x11reg_cmn.hpp"
#include "common/gen/x11srs_cmn.hpp"
#include "common/gen/xclude_cmn.hpp"
#include "common/gen/xeastr_cmn.hpp"
#include "common/gen/xrgfct_cmn.hpp"
#include "common/gen/xrgmdl_cmn.hpp"
#include "common/gen/xrgum_cmn.hpp"
#include "common/gen/xtdtyp_cmn.hpp"
#include "common/gen/xtrm_cmn.hpp"
// Hand-maintained: lexer/parser state from the .i-based COMMONs (lex.i /clex/,
// cchars.i /cchars/) plus rngbuf SAVE state. The generator only covered .cmn
// files, so this member is added by hand (M1 spec-parser milestone).
#include "specparse/lexstate.hpp"
// Hand-maintained: slidingspans{} sfs/chs result struct (SlidingSpansOutput),
// not a COMMON mirror -- see core/src/x11/slidingspans.hpp.
#include "x11/slidingspans.hpp"
// Hand-maintained: history{} sar/sae/trr/tre result struct (HistoryOutput),
// not a COMMON mirror -- see core/src/driver/run_history.hpp.
#include "driver/run_history.hpp"
// Hand-maintained: spectrum{} sp0/sp1/sp2 result struct (SpectrumOutput),
// not a COMMON mirror -- see core/src/driver/run_spectrum.hpp.
#include "driver/run_spectrum.hpp"

namespace x13 {

// One member per COMMON-block include; every ported routine takes X13Context&.
struct X13Context {
    ErrorState error_state;    // program-wide fatal flag (see error_cmn too)
    ChannelRegistry channels_; // Fortran unit-number output buffers
    LexState lex;              // spec-file lexer/parser state (lex.i /clex/, cchars.i)
    ParseSettings captured;    // M1 instrumentation: key parsed settings for the gate
    SaveState saves;           // M2: captured save tables (numeric surface + text)
    // SAVEd Fortran locals (persist across calls, belong to no COMMON block).
    // stpitr_oldobj: stpitr.f SAVEs oldobj (last iteration's objfcn) between
    // calls to form the relative-deviance ratio. It is (re)set inside stpitr on
    // every call -- the first iteration of an estimation (Iter<=1, or Objfcn==0)
    // drives it through the ELSE reset, and every call ends by storing the
    // current Objfcn -- so the 0.0 default here only matters until the first
    // call, exactly as the Fortran SAVE (undefined but never read on iter 1).
    // setmdl_first: setmdl.f SAVEs `first` (DATA .true.), cleared at the end of
    // the first call. It gates the initial-value root check: on the first call
    // an MA root ON the unit circle is an error; afterwards (IGLS re-entries)
    // near-unit MA operators are instead shrunk. Persists per estimation.
    struct {
        int armafl_nextma = 0;
        double stpitr_oldobj = 0.0;
        bool setmdl_first = true;
        // xtrm.Ksdev (extreme-value sigma-vector mode) as parsed, captured
        // before the main run's entsch mutates it -- so each sliding-spans
        // sub-span replay can start its own fresh adjustment from the spec
        // default instead of leaking the main run's evolved value (which
        // flips entsch's kersa/ksdev decode -> wrong extreme weights ->
        // wrong seasonal filter). See run_x11_span / ssprep_snapshot.
        int ksdev0 = 1;
        // x11opt.Lterm (seasonal-filter MSR selector) and Nterm (Henderson
        // trend-filter length) as parsed, captured before the main run's
        // x11pt2/vtc resolve them. history{}'s expanding-window replay resets
        // these per span so each span re-selects its own filter length (the
        // selection is length-dependent); without the reset every span reuses
        // the first (shortest) span's resolved choice. See run_history /
        // ssprep_snapshot.
        int lterm0 = 0;
        int nterm0 = 0;
    } saved;
    // work3.cmn's Stsie (D8 "unmodified SI ratio" buffer). x11pt2/x11pt3 treat
    // most of their COMMON scratch (Temp/Stex/Stime/Ckhs/Ststd/Biasfc/Sp2) as
    // function-local PLEN arrays -- harmless for a single main run (always
    // Pos1bk==1, so nothing outside [Pos1bk,Posffc] is ever meaningfully read
    // back). Stsie is the one exception: x11pt3.f's Ksdev>1 branch does
    // `CALL copy(Stsie,Posfob,1,Stsi)`, an index-1-based (not Pos1bk-based)
    // reset that relies on positions [1,Pos1bk-1] holding whatever a PRIOR
    // call (the main run, or an earlier sliding-spans replay) already
    // computed there -- exactly how a real Fortran COMMON persists across
    // calls. A function-local Stsie loses that history on every call, so a
    // replayed span with Pos1bk>1 (slidingspans{}/history{}) reads
    // uninitialized stack memory into the dead zone, which replac() then
    // pulls across the Pos1bk boundary via its period lookback -- NaN. Making
    // this one buffer ctx-persistent (zero-initialized once, like a COMMON's
    // OS-provided zero-init) reproduces the real persistence faithfully.
    std::vector<double> work3_stsie = std::vector<double>(1020, 0.0);
    // mq10.cmn's Stex (the per-iteration extreme component: x11pt2's B/C/D
    // loop writes it every pass, x11pt3's D8/D9 stage reads whatever x11pt2's
    // LAST pass (Part D) left there). Same story as work3_stsie above: a
    // function-local Stex in x11pt3 is simply uninitialized (x11pt2's own
    // local Stex is a DIFFERENT stack allocation, gone once x11pt2 returns),
    // not just missing history in a dead zone -- this is wrong for every
    // call, single main run included, but was latent because sfmsr's D8
    // Ksdev>1 replac() path (the only consumer that actually feeds D10/D11,
    // via Stsie) never triggered for the corpus's existing gated specs; a
    // sliding-spans sub-span replay does trigger it (shorter/differently-
    // windowed data changes vtest/entsch's auto-selected Ksdev). Fixing this
    // is what un-blocked the slidingspans{} sfs/chs gate.
    std::vector<double> mq10_stex = std::vector<double>(1020, 0.0);
    // /mq5a/ Stime (E3, the modified irregular): x11pt3's Part-E builds it into a
    // function-local array in the oracle; persisted here so run_spectrum can read
    // it (spcdrv.f differences E2/E3, not the D11/D13 saves -- x11pt4 runs before
    // spcdrv). The AO/TC divsub on Stime is commented out in the oracle, so this
    // holds Sti where C17-good, ebar where extreme, with no further adjustment.
    std::vector<double> mq5a_stime = std::vector<double>(1020, 0.0);
    // x11pt3's `ststd` (D16, the combined seasonal + calendar adjustment
    // factors). A function-local PLEN array in the oracle; snapshotted here at
    // the point the oracle punches D16 (x11pt3.f:1129-1146, i.e. AFTER the
    // Khol==1 return, so a holiday-only run leaves it empty exactly as the
    // oracle writes no D16) so the harness can emit the table.
    std::vector<double> x11_ststd;
    // /tests/ as of the END of the MAIN X-11 run -- i.e. where x11pt4 (and its
    // svf2f3 savelog write) sits in the oracle. Needed because the oracle emits
    // f2.fsd8/kw/msf/idseasonal at that point, while slidingspans{}/history{}
    // replay x11pt3 afterwards and each replay OVERWRITES the live /tests/ with
    // its own span's statistics. Snapshot, not live read.
    tests_cmn x11_f2tests{};
    bool x11_f2tests_set = false;
    // The INTERNAL (pre-publication) D13 and D12 as they stand at the end of
    // x11pt3, i.e. before the AO/TC outliers are folded back into the published
    // D13 and the level shift into the published D12. x11pt4 reads those
    // internal buffers (the oracle keeps Sti/Stc internal and prints from local
    // sti2/stc2 copies; the C++ x11pt3 does it the other way round so the
    // harness can dump the published tables straight off /x11srs/).
    std::vector<double> x11_sti_int;
    std::vector<double> x11_stc_int;
    // The Part-F summary measures + quality statistics (x11pt4's /inpt2/,
    // /work2/ and Mcd output), snapshotted where the oracle's svf2f3 writes the
    // .udg `f2.*`/`f3.*` block. Snapshot for the same reason as x11_f2tests: a
    // slidingspans{}/history{} replay re-runs the X-11 spine per span.
    inpt2_cmn x11_f2inpt2{};
    work2_cmn x11_f2work2{};
    int x11_f2mcd = 0;
    double x11_f2ratic = 0.0;   // /optxdp/ Ratic (f2.ic), snapshotted with them
    double x11_f2ratis = 0.0;   // /optxdp/ Ratis (f2.is)
    bool x11_f3_set = false;
    // x11pt4.f's PART-E tables. E1/E2/E3 are just Stome/Stcime/Stime, already on
    // ctx; these are the ones the oracle builds into function-locals or the
    // /work/ Temp scratch, all 1-based over PLEN so the harness can punch them
    // over the oracle's own ranges. e5-e8 (and their pe* percent twins) start at
    // Pos1ob+1; e11/e18/eb over [Pos1ob,Posfob] (e18/eb widening to Pos1bk /
    // Posffc under x11{appendbcst/appendfcst}). e6a/e6r exist only with
    // force{type=denton} / x11{sarounded=yes}.
    std::vector<double> x11_e5, x11_e6, x11_e6a, x11_e6r, x11_e7, x11_e8;
    std::vector<double> x11_e11, x11_e18, x11_eb;
    bool x11_etables_set = false;
    // x11pt4.f:266's `gudbak` -- the good-obs flags as they stood before the
    // Part-E section forced them all true for a user-constant run. A function-
    // local in the oracle; carried here only because the port splits x11pt4 into
    // its Part-E and Part-F halves, and :334 restores from it. Empty (and the
    // restore skipped) on every path without x11{constant=}.
    std::vector<bool> x11_gudbak;
    // agr3.f locals the composite gate needs back: `stc2in` (the published
    // INDIRECT trend -- Stc still holds the pre-level-shift filter output) and
    // `ststd` (the indirect total adjustment factors). Function-locals in the
    // oracle, like x11pt3's ststd above.
    std::vector<double> agr_stc2in;
    std::vector<double> agr_ststd;
    // The composite total's own DIRECT d10-d13, snapshotted before agr3
    // overwrites those buffers with the indirect adjustment. Not an oracle step:
    // the oracle has already emitted them by then, while this port hands all
    // output to the caller after the run.
    std::vector<double> agr_direct_d10, agr_direct_d11, agr_direct_d12, agr_direct_d13;
    // /kcser/ Ckhs -- x11pt3's snapshot of the final SA series (D11) taken at
    // x11pt3.f:379, BEFORE the Fin*/Adj* folds rewrite Stci. A COMMON in the
    // oracle because agr3.f reads it after x11pt3 has returned: it is the series
    // the DIRECT trend used by the composite comparison statistics is filtered
    // from. Dead on every non-composite path.
    std::vector<double> kcser_ckhs = std::vector<double>(1020, 0.0);
    // The Iagr==4 direct-vs-indirect comparison statistics (agr2.f:87-181), in
    // the oracle's `di(1..24)` layout, plus the Henderson length agr3 reports as
    // `indtrendma`. Empty unless a composite total actually ran.
    std::vector<double> agr_cmpstat;
    int agr_indtrendma = 0;
    // Final regARIMA residuals (arima.f's `a`, length `resid_na`) captured after
    // estimation for the residual-spectrum diagnostic (spr, spcrsd.f). Their
    // start date is Begspn + (Nspobs - resid_na) (arima.f:1124).
    std::vector<double> resid_a;
    int resid_na = 0;

    // Effective observation count the regARIMA fit actually used (Nspobs-Nintvl
    // at estimation time). Normally derivable from Nspobs, but series{modelspan=}
    // estimates on a narrower span and setspn.f puts Nspobs back to the full span
    // before X-11 -- so it has to be recorded when it is still true.
    int est_nefobs = 0;
    // x11regression{} B/C-iteration regression trading-day factors (b16/c16),
    // snapshotted by x11mdl_td over [Pos1ob,Posfob] at the B (Kpart=2) and C
    // (Kpart=3) iterations of x11pt2.
    std::vector<double> x11reg_b16;
    std::vector<double> x11reg_c16;
    // x11regression{} design matrix (xrm save): the Nb TD-contrast columns over
    // the Nspobs data rows, row-major (row r, col c) at index r*x11reg_xrm_ncol+c.
    // Snapshotted from md.xy at x11mdl_td (the design is iteration-independent).
    std::vector<double> x11reg_xrm;
    int x11reg_xrm_ncol = 0;
    bool x11reg_ran = false;
    // x11regression{ aictest=(easter) } AICC test (x11aic.f easter branch): one
    // (window, AICC) pair per candidate over Xeasvc (window 0 == "noeaster"),
    // plus the chosen window (Aicind; 0 == easter rejected). Populated at the B
    // iteration of x11mdl_td when ctx.x11log.xeastr is set.
    std::vector<std::pair<int, double>> x11reg_aicc_xe;
    int x11reg_xe_window = -1;
    bool x11reg_xe_ran = false;
    // x11regression{} user prior trading-day factor (a4 save): the Kswv=1 pritd
    // factor over the observed span [Pos1ob,Posfob]. Bit-exact vs the oracle a4.
    std::vector<double> x11_a4_prior;
    // x11regression{} OLS-estimated prior trading-day factor (Ixreg>=2, xrgdrv):
    // the transparent-SA-estimated Faccal over the observed span, 1-based at
    // Pos1ob. Stashed by xrgdrv (pre-model phase) so run_pre_model can divide the
    // estimation input by it (the oracle fits arima on the prior-TD-adjusted
    // series) and the main x11pt1 can restore it for the Ixreg==3 fold after
    // x11int wipes /x11fac/. Empty when no Ixreg>=2 x11regression was requested.
    std::vector<double> x11_faccal_prior;
    // SEATS combined-adjustment source (s16/s18): the RAW original series in
    // ORIGINAL units (a1 -- mean, calendar/outlier regression effects AND the
    // lom/leap prior all IN), 0-based over the historical span [1,nspobs]. The
    // decomposition operates on the LINEARIZED series ctx.series.tsrs (non-mean
    // regression effects removed, prior applied); s10 (seasonal factor) =
    // linearized/sa, but s16/s18 (COMBINED adjustment factors) = a1/sa refold
    // BOTH the removed regression effects and the prior (s16 = s10 x td-factor x
    // lom/leap prior). Filled by run_pre_model when a prior or a non-mean
    // regressor is present; empty otherwise, so estbur falls back to the
    // linearized series and s10==s16==s18 (the no-regressor / Constant-only
    // corpus stays bit-identical).
    std::vector<double> seats_combined_orig;
    // M3 forecast-output results (fcstout / prtfct LFOROS path): the original-
    // scale point forecast + confidence interval, plus the transformed-scale
    // forecast/SE. Stored on the context (no auto file output); a thin driver
    // surfaces them. All length nfcst.
    struct FcstOut {
        int nfcst = 0;
        std::vector<double> fcst;    // point forecast, original scale (untfct)
        std::vector<double> lwrci;   // lower confidence bound, original scale
        std::vector<double> uprci;   // upper confidence bound, original scale
        std::vector<double> trnfct;  // forecast on the transformed scale
        std::vector<double> trnse;   // forecast standard error, transformed scale
        // mkback.f backcasts (forecast{maxback=}), transformed scale. Ordered
        // most-recent-first, which is what extend.f's revrse expects.
        int nbcst = 0;
        std::vector<double> trnbct;
        std::vector<double> trnbse;
    } forecasts;
    // trnaic.f automatic transform-selection result (transform{function=auto}).
    // The two default-airline-model AICC values the oracle reports as
    // aictest.trans.aicc.nolog / .log, plus the chosen transform. Populated only
    // when run_m2 runs trnaic (Fcntyp==0 on entry); no auto file output.
    struct TrnAicResult {
        bool ran = false;
        double aicno = 0.0;    // AICC, untransformed model
        double aiclog = 0.0;   // AICC, log-transformed model
        bool selected_log = false;
    } trnaic_result;
    // slidingspans{} sfs/chs result (core/src/x11/slidingspans.hpp) -- the
    // Max_%_DIFF column + the derived month-to-month SA-change array; the raw
    // per-span S/Sa/Td arrays live on the real COMMON mirror, sspdat below.
    SlidingSpansOutput ssout;
    HistoryOutput hist_out;
    SpectrumOutput spcout;
    adj_cmn adj;
    adxser_cmn adxser;
    agr_cmn agr;
    agrsrs_cmn agrsrs;
    arima_cmn arima;
    autoq_cmn autoq;
    bstmdl_cmn bstmdl;
    chrt_cmn chrt;
    error_cmn error;
    extend_cmn extend;
    filetb_cmn filetb;
    force_cmn force;
    fxreg_cmn fxreg;
    getarg_cmn getarg;
    global_cmn global;
    goodob_cmn goodob;
    hiddn_cmn hiddn;
    htmlfile_cmn htmlfile;
    htmlout_cmn htmlout;
    inpt_cmn inpt;
    inpt2_cmn inpt2;
    lkhd_cmn lkhd;
    lzero_cmn lzero;
    mdldat_cmn mdldat;
    mdldg_cmn mdldg;
    metadata_cmn metadata;
    missng_cmn missng;
    model_cmn model;
    mq3_cmn mq3;
    newmdl_cmn newmdl;
    orisrs_cmn orisrs;
    otlrev_cmn otlrev;
    otxrev_cmn otxrev;
    picktd_cmn picktd;
    priadj_cmn priadj;
    prior_cmn prior;
    prittl_cmn prittl;
    priusr_cmn priusr;
    rev_cmn rev;
    revsrs_cmn revsrs;
    revtrg_cmn revtrg;
    revusr_cmn revusr;
    rho_cmn rho;
    savcmn_cmn savcmn;
    seatad_cmn seatad;
    seatcm_cmn seatcm;
    seatdg_cmn seatdg;
    seatlg_cmn seatlg;
    seatmd_cmn seatmd;
    seatop_cmn seatop;
    series_cmn series;
    spcidx_cmn spcidx;
    ss2rv_cmn ss2rv;
    ssap_cmn ssap;
    ssft_cmn ssft;
    sspdat_cmn sspdat;
    sspinp_cmn sspinp;
    ssprep_cmn ssprep;
    sspvec_cmn sspvec;
    stcfcm_cmn stcfcm;
    svllog_cmn svllog;
    tbllog_cmn tbllog;
    tdtyp_cmn tdtyp;
    tests_cmn tests;
    tfmts_cmn tfmts;
    title_cmn title;
    tukey_cmn tukey;
    units_cmn units;
    urgbak_cmn urgbak;
    usrreg_cmn usrreg;
    usrxrg_cmn usrxrg;
    work2_cmn work2;
    x11adj_cmn x11adj;
    x11fac_cmn x11fac;
    x11log_cmn x11log;
    x11msc_cmn x11msc;
    x11opt_cmn x11opt;
    x11ptr_cmn x11ptr;
    x11reg_cmn x11reg;
    x11srs_cmn x11srs;
    xclude_cmn xclude;
    xeastr_cmn xeastr;
    xrgfct_cmn xrgfct;
    xrgmdl_cmn xrgmdl;
    xrgum_cmn xrgum;
    xtdtyp_cmn xtdtyp;
    xtrm_cmn xtrm;
};

}  // namespace x13
#endif  // X13_CONTEXT_HPP
