// Generated by tools/cmn2hpp.py. Aggregates every COMMON-block struct. DO NOT EDIT.
#ifndef X13_CONTEXT_HPP
#define X13_CONTEXT_HPP
#include "x13/x13error.hpp"
#include "x13/channels.hpp"
#include "x13/savestate.hpp"
#include "common/gen/adj_cmn.hpp"
#include "common/gen/adxser_cmn.hpp"
#include "common/gen/agr_cmn.hpp"
#include "common/gen/agrsrs_cmn.hpp"
#include "common/gen/arima_cmn.hpp"
#include "common/gen/autoq_cmn.hpp"
#include "common/gen/bstmdl_cmn.hpp"
#include "common/gen/chrt_cmn.hpp"
#include "common/gen/error_cmn.hpp"
#include "common/gen/extend_cmn.hpp"
#include "common/gen/filetb_cmn.hpp"
#include "common/gen/force_cmn.hpp"
#include "common/gen/fxreg_cmn.hpp"
#include "common/gen/getarg_cmn.hpp"
#include "common/gen/global_cmn.hpp"
#include "common/gen/goodob_cmn.hpp"
#include "common/gen/hiddn_cmn.hpp"
#include "common/gen/htmlfile_cmn.hpp"
#include "common/gen/htmlout_cmn.hpp"
#include "common/gen/inpt_cmn.hpp"
#include "common/gen/inpt2_cmn.hpp"
#include "common/gen/lkhd_cmn.hpp"
#include "common/gen/lzero_cmn.hpp"
#include "common/gen/mdldat_cmn.hpp"
#include "common/gen/mdldg_cmn.hpp"
#include "common/gen/metadata_cmn.hpp"
#include "common/gen/missng_cmn.hpp"
#include "common/gen/model_cmn.hpp"
#include "common/gen/mq3_cmn.hpp"
#include "common/gen/newmdl_cmn.hpp"
#include "common/gen/orisrs_cmn.hpp"
#include "common/gen/otlrev_cmn.hpp"
#include "common/gen/otxrev_cmn.hpp"
#include "common/gen/picktd_cmn.hpp"
#include "common/gen/priadj_cmn.hpp"
#include "common/gen/prior_cmn.hpp"
#include "common/gen/prittl_cmn.hpp"
#include "common/gen/priusr_cmn.hpp"
#include "common/gen/rev_cmn.hpp"
#include "common/gen/revsrs_cmn.hpp"
#include "common/gen/revtrg_cmn.hpp"
#include "common/gen/revusr_cmn.hpp"
#include "common/gen/rho_cmn.hpp"
#include "common/gen/savcmn_cmn.hpp"
#include "common/gen/seatad_cmn.hpp"
#include "common/gen/seatcm_cmn.hpp"
#include "common/gen/seatdg_cmn.hpp"
#include "common/gen/seatlg_cmn.hpp"
#include "common/gen/seatmd_cmn.hpp"
#include "common/gen/seatop_cmn.hpp"
#include "common/gen/series_cmn.hpp"
#include "common/gen/spcidx_cmn.hpp"
#include "common/gen/ss2rv_cmn.hpp"
#include "common/gen/ssap_cmn.hpp"
#include "common/gen/ssft_cmn.hpp"
#include "common/gen/sspdat_cmn.hpp"
#include "common/gen/sspinp_cmn.hpp"
#include "common/gen/ssprep_cmn.hpp"
#include "common/gen/sspvec_cmn.hpp"
#include "common/gen/stcfcm_cmn.hpp"
#include "common/gen/svllog_cmn.hpp"
#include "common/gen/tbllog_cmn.hpp"
#include "common/gen/tdtyp_cmn.hpp"
#include "common/gen/tests_cmn.hpp"
#include "common/gen/tfmts_cmn.hpp"
#include "common/gen/title_cmn.hpp"
#include "common/gen/tukey_cmn.hpp"
#include "common/gen/units_cmn.hpp"
#include "common/gen/urgbak_cmn.hpp"
#include "common/gen/usrreg_cmn.hpp"
#include "common/gen/usrxrg_cmn.hpp"
#include "common/gen/work2_cmn.hpp"
#include "common/gen/x11adj_cmn.hpp"
#include "common/gen/x11fac_cmn.hpp"
#include "common/gen/x11log_cmn.hpp"
#include "common/gen/x11msc_cmn.hpp"
#include "common/gen/x11opt_cmn.hpp"
#include "common/gen/x11ptr_cmn.hpp"
#include "common/gen/x11reg_cmn.hpp"
#include "common/gen/x11srs_cmn.hpp"
#include "common/gen/xclude_cmn.hpp"
#include "common/gen/xeastr_cmn.hpp"
#include "common/gen/xrgfct_cmn.hpp"
#include "common/gen/xrgmdl_cmn.hpp"
#include "common/gen/xrgum_cmn.hpp"
#include "common/gen/xtdtyp_cmn.hpp"
#include "common/gen/xtrm_cmn.hpp"
// Hand-maintained: lexer/parser state from the .i-based COMMONs (lex.i /clex/,
// cchars.i /cchars/) plus rngbuf SAVE state. The generator only covered .cmn
// files, so this member is added by hand (M1 spec-parser milestone).
#include "specparse/lexstate.hpp"

namespace x13 {

// One member per COMMON-block include; every ported routine takes X13Context&.
struct X13Context {
    ErrorState error_state;    // program-wide fatal flag (see error_cmn too)
    ChannelRegistry channels_; // Fortran unit-number output buffers
    LexState lex;              // spec-file lexer/parser state (lex.i /clex/, cchars.i)
    ParseSettings captured;    // M1 instrumentation: key parsed settings for the gate
    SaveState saves;           // M2: captured save tables (numeric surface + text)
    // SAVEd Fortran locals (persist across calls, belong to no COMMON block).
    struct { int armafl_nextma = 0; } saved;
    adj_cmn adj;
    adxser_cmn adxser;
    agr_cmn agr;
    agrsrs_cmn agrsrs;
    arima_cmn arima;
    autoq_cmn autoq;
    bstmdl_cmn bstmdl;
    chrt_cmn chrt;
    error_cmn error;
    extend_cmn extend;
    filetb_cmn filetb;
    force_cmn force;
    fxreg_cmn fxreg;
    getarg_cmn getarg;
    global_cmn global;
    goodob_cmn goodob;
    hiddn_cmn hiddn;
    htmlfile_cmn htmlfile;
    htmlout_cmn htmlout;
    inpt_cmn inpt;
    inpt2_cmn inpt2;
    lkhd_cmn lkhd;
    lzero_cmn lzero;
    mdldat_cmn mdldat;
    mdldg_cmn mdldg;
    metadata_cmn metadata;
    missng_cmn missng;
    model_cmn model;
    mq3_cmn mq3;
    newmdl_cmn newmdl;
    orisrs_cmn orisrs;
    otlrev_cmn otlrev;
    otxrev_cmn otxrev;
    picktd_cmn picktd;
    priadj_cmn priadj;
    prior_cmn prior;
    prittl_cmn prittl;
    priusr_cmn priusr;
    rev_cmn rev;
    revsrs_cmn revsrs;
    revtrg_cmn revtrg;
    revusr_cmn revusr;
    rho_cmn rho;
    savcmn_cmn savcmn;
    seatad_cmn seatad;
    seatcm_cmn seatcm;
    seatdg_cmn seatdg;
    seatlg_cmn seatlg;
    seatmd_cmn seatmd;
    seatop_cmn seatop;
    series_cmn series;
    spcidx_cmn spcidx;
    ss2rv_cmn ss2rv;
    ssap_cmn ssap;
    ssft_cmn ssft;
    sspdat_cmn sspdat;
    sspinp_cmn sspinp;
    ssprep_cmn ssprep;
    sspvec_cmn sspvec;
    stcfcm_cmn stcfcm;
    svllog_cmn svllog;
    tbllog_cmn tbllog;
    tdtyp_cmn tdtyp;
    tests_cmn tests;
    tfmts_cmn tfmts;
    title_cmn title;
    tukey_cmn tukey;
    units_cmn units;
    urgbak_cmn urgbak;
    usrreg_cmn usrreg;
    usrxrg_cmn usrxrg;
    work2_cmn work2;
    x11adj_cmn x11adj;
    x11fac_cmn x11fac;
    x11log_cmn x11log;
    x11msc_cmn x11msc;
    x11opt_cmn x11opt;
    x11ptr_cmn x11ptr;
    x11reg_cmn x11reg;
    x11srs_cmn x11srs;
    xclude_cmn xclude;
    xeastr_cmn xeastr;
    xrgfct_cmn xrgfct;
    xrgmdl_cmn xrgmdl;
    xrgum_cmn xrgum;
    xtdtyp_cmn xtdtyp;
    xtrm_cmn xtrm;
};

}  // namespace x13
#endif  // X13_CONTEXT_HPP
