// Generated by tools/cmn2hpp.py. Aggregates every COMMON-block struct. DO NOT EDIT.
#ifndef X13_CONTEXT_HPP
#define X13_CONTEXT_HPP
#include "x13/x13error.hpp"
#include "x13/channels.hpp"
#include "x13/savestate.hpp"
#include "common/gen/adj_cmn.hpp"
#include "common/gen/adxser_cmn.hpp"
#include "common/gen/agr_cmn.hpp"
#include "common/gen/agrsrs_cmn.hpp"
#include "common/gen/arima_cmn.hpp"
#include "common/gen/autoq_cmn.hpp"
#include "common/gen/bstmdl_cmn.hpp"
#include "common/gen/chrt_cmn.hpp"
#include "common/gen/error_cmn.hpp"
#include "common/gen/extend_cmn.hpp"
#include "common/gen/filetb_cmn.hpp"
#include "common/gen/force_cmn.hpp"
#include "common/gen/fxreg_cmn.hpp"
#include "common/gen/getarg_cmn.hpp"
#include "common/gen/global_cmn.hpp"
#include "common/gen/goodob_cmn.hpp"
#include "common/gen/hiddn_cmn.hpp"
#include "common/gen/htmlfile_cmn.hpp"
#include "common/gen/htmlout_cmn.hpp"
#include "common/gen/inpt_cmn.hpp"
#include "common/gen/inpt2_cmn.hpp"
#include "common/gen/lkhd_cmn.hpp"
#include "common/gen/lzero_cmn.hpp"
#include "common/gen/mdldat_cmn.hpp"
#include "common/gen/mdldg_cmn.hpp"
#include "common/gen/metadata_cmn.hpp"
#include "common/gen/missng_cmn.hpp"
#include "common/gen/model_cmn.hpp"
#include "common/gen/mq3_cmn.hpp"
#include "common/gen/newmdl_cmn.hpp"
#include "common/gen/orisrs_cmn.hpp"
#include "common/gen/otlrev_cmn.hpp"
#include "common/gen/otxrev_cmn.hpp"
#include "common/gen/picktd_cmn.hpp"
#include "common/gen/priadj_cmn.hpp"
#include "common/gen/prior_cmn.hpp"
#include "common/gen/prittl_cmn.hpp"
#include "common/gen/priusr_cmn.hpp"
#include "common/gen/rev_cmn.hpp"
#include "common/gen/revsrs_cmn.hpp"
#include "common/gen/revtrg_cmn.hpp"
#include "common/gen/revusr_cmn.hpp"
#include "common/gen/rho_cmn.hpp"
#include "common/gen/savcmn_cmn.hpp"
#include "common/gen/seatad_cmn.hpp"
#include "common/gen/seatcm_cmn.hpp"
#include "common/gen/seatdg_cmn.hpp"
#include "common/gen/seatlg_cmn.hpp"
#include "common/gen/seatmd_cmn.hpp"
#include "common/gen/seatop_cmn.hpp"
#include "common/gen/series_cmn.hpp"
#include "common/gen/spcidx_cmn.hpp"
#include "common/gen/ss2rv_cmn.hpp"
#include "common/gen/ssap_cmn.hpp"
#include "common/gen/ssft_cmn.hpp"
#include "common/gen/sspdat_cmn.hpp"
#include "common/gen/sspinp_cmn.hpp"
#include "common/gen/ssprep_cmn.hpp"
#include "common/gen/sspvec_cmn.hpp"
#include "common/gen/stcfcm_cmn.hpp"
#include "common/gen/svllog_cmn.hpp"
#include "common/gen/tbllog_cmn.hpp"
#include "common/gen/tdtyp_cmn.hpp"
#include "common/gen/tests_cmn.hpp"
#include "common/gen/tfmts_cmn.hpp"
#include "common/gen/title_cmn.hpp"
#include "common/gen/tukey_cmn.hpp"
#include "common/gen/units_cmn.hpp"
#include "common/gen/urgbak_cmn.hpp"
#include "common/gen/usrreg_cmn.hpp"
#include "common/gen/usrxrg_cmn.hpp"
#include "common/gen/work2_cmn.hpp"
#include "common/gen/x11adj_cmn.hpp"
#include "common/gen/x11fac_cmn.hpp"
#include "common/gen/x11log_cmn.hpp"
#include "common/gen/x11msc_cmn.hpp"
#include "common/gen/x11opt_cmn.hpp"
#include "common/gen/x11ptr_cmn.hpp"
#include "common/gen/x11reg_cmn.hpp"
#include "common/gen/x11srs_cmn.hpp"
#include "common/gen/xclude_cmn.hpp"
#include "common/gen/xeastr_cmn.hpp"
#include "common/gen/xrgfct_cmn.hpp"
#include "common/gen/xrgmdl_cmn.hpp"
#include "common/gen/xrgum_cmn.hpp"
#include "common/gen/xtdtyp_cmn.hpp"
#include "common/gen/xtrm_cmn.hpp"
// Hand-maintained: lexer/parser state from the .i-based COMMONs (lex.i /clex/,
// cchars.i /cchars/) plus rngbuf SAVE state. The generator only covered .cmn
// files, so this member is added by hand (M1 spec-parser milestone).
#include "specparse/lexstate.hpp"
// Hand-maintained: slidingspans{} sfs/chs result struct (SlidingSpansOutput),
// not a COMMON mirror -- see core/src/x11/slidingspans.hpp.
#include "x11/slidingspans.hpp"
// Hand-maintained: history{} sar/sae/trr/tre result struct (HistoryOutput),
// not a COMMON mirror -- see core/src/driver/run_history.hpp.
#include "driver/run_history.hpp"
// Hand-maintained: spectrum{} sp0/sp1/sp2 result struct (SpectrumOutput),
// not a COMMON mirror -- see core/src/driver/run_spectrum.hpp.
#include "driver/run_spectrum.hpp"

namespace x13 {

// One member per COMMON-block include; every ported routine takes X13Context&.
struct X13Context {
    ErrorState error_state;    // program-wide fatal flag (see error_cmn too)
    ChannelRegistry channels_; // Fortran unit-number output buffers
    LexState lex;              // spec-file lexer/parser state (lex.i /clex/, cchars.i)
    ParseSettings captured;    // M1 instrumentation: key parsed settings for the gate
    SaveState saves;           // M2: captured save tables (numeric surface + text)
    // SAVEd Fortran locals (persist across calls, belong to no COMMON block).
    // stpitr_oldobj: stpitr.f SAVEs oldobj (last iteration's objfcn) between
    // calls to form the relative-deviance ratio. It is (re)set inside stpitr on
    // every call -- the first iteration of an estimation (Iter<=1, or Objfcn==0)
    // drives it through the ELSE reset, and every call ends by storing the
    // current Objfcn -- so the 0.0 default here only matters until the first
    // call, exactly as the Fortran SAVE (undefined but never read on iter 1).
    // setmdl_first: setmdl.f SAVEs `first` (DATA .true.), cleared at the end of
    // the first call. It gates the initial-value root check: on the first call
    // an MA root ON the unit circle is an error; afterwards (IGLS re-entries)
    // near-unit MA operators are instead shrunk. Persists per estimation.
    struct {
        int armafl_nextma = 0;
        double stpitr_oldobj = 0.0;
        bool setmdl_first = true;
        // xtrm.Ksdev (extreme-value sigma-vector mode) as parsed, captured
        // before the main run's entsch mutates it -- so each sliding-spans
        // sub-span replay can start its own fresh adjustment from the spec
        // default instead of leaking the main run's evolved value (which
        // flips entsch's kersa/ksdev decode -> wrong extreme weights ->
        // wrong seasonal filter). See run_x11_span / ssprep_snapshot.
        int ksdev0 = 1;
        // x11opt.Lterm (seasonal-filter MSR selector) and Nterm (Henderson
        // trend-filter length) as parsed, captured before the main run's
        // x11pt2/vtc resolve them. history{}'s expanding-window replay resets
        // these per span so each span re-selects its own filter length (the
        // selection is length-dependent); without the reset every span reuses
        // the first (shortest) span's resolved choice. See run_history /
        // ssprep_snapshot.
        int lterm0 = 0;
        int nterm0 = 0;
    } saved;
    // work3.cmn's Stsie (D8 "unmodified SI ratio" buffer). x11pt2/x11pt3 treat
    // most of their COMMON scratch (Temp/Stex/Stime/Ckhs/Ststd/Biasfc/Sp2) as
    // function-local PLEN arrays -- harmless for a single main run (always
    // Pos1bk==1, so nothing outside [Pos1bk,Posffc] is ever meaningfully read
    // back). Stsie is the one exception: x11pt3.f's Ksdev>1 branch does
    // `CALL copy(Stsie,Posfob,1,Stsi)`, an index-1-based (not Pos1bk-based)
    // reset that relies on positions [1,Pos1bk-1] holding whatever a PRIOR
    // call (the main run, or an earlier sliding-spans replay) already
    // computed there -- exactly how a real Fortran COMMON persists across
    // calls. A function-local Stsie loses that history on every call, so a
    // replayed span with Pos1bk>1 (slidingspans{}/history{}) reads
    // uninitialized stack memory into the dead zone, which replac() then
    // pulls across the Pos1bk boundary via its period lookback -- NaN. Making
    // this one buffer ctx-persistent (zero-initialized once, like a COMMON's
    // OS-provided zero-init) reproduces the real persistence faithfully.
    std::vector<double> work3_stsie = std::vector<double>(1020, 0.0);
    // mq10.cmn's Stex (the per-iteration extreme component: x11pt2's B/C/D
    // loop writes it every pass, x11pt3's D8/D9 stage reads whatever x11pt2's
    // LAST pass (Part D) left there). Same story as work3_stsie above: a
    // function-local Stex in x11pt3 is simply uninitialized (x11pt2's own
    // local Stex is a DIFFERENT stack allocation, gone once x11pt2 returns),
    // not just missing history in a dead zone -- this is wrong for every
    // call, single main run included, but was latent because sfmsr's D8
    // Ksdev>1 replac() path (the only consumer that actually feeds D10/D11,
    // via Stsie) never triggered for the corpus's existing gated specs; a
    // sliding-spans sub-span replay does trigger it (shorter/differently-
    // windowed data changes vtest/entsch's auto-selected Ksdev). Fixing this
    // is what un-blocked the slidingspans{} sfs/chs gate.
    std::vector<double> mq10_stex = std::vector<double>(1020, 0.0);
    // /mq5a/ Stime (E3, the modified irregular): x11pt3's Part-E builds it into a
    // function-local array in the oracle; persisted here so run_spectrum can read
    // it (spcdrv.f differences E2/E3, not the D11/D13 saves -- x11pt4 runs before
    // spcdrv). The AO/TC divsub on Stime is commented out in the oracle, so this
    // holds Sti where C17-good, ebar where extreme, with no further adjustment.
    std::vector<double> mq5a_stime = std::vector<double>(1020, 0.0);
    // M3 forecast-output results (fcstout / prtfct LFOROS path): the original-
    // scale point forecast + confidence interval, plus the transformed-scale
    // forecast/SE. Stored on the context (no auto file output); a thin driver
    // surfaces them. All length nfcst.
    struct FcstOut {
        int nfcst = 0;
        std::vector<double> fcst;    // point forecast, original scale (untfct)
        std::vector<double> lwrci;   // lower confidence bound, original scale
        std::vector<double> uprci;   // upper confidence bound, original scale
        std::vector<double> trnfct;  // forecast on the transformed scale
        std::vector<double> trnse;   // forecast standard error, transformed scale
    } forecasts;
    // trnaic.f automatic transform-selection result (transform{function=auto}).
    // The two default-airline-model AICC values the oracle reports as
    // aictest.trans.aicc.nolog / .log, plus the chosen transform. Populated only
    // when run_m2 runs trnaic (Fcntyp==0 on entry); no auto file output.
    struct TrnAicResult {
        bool ran = false;
        double aicno = 0.0;    // AICC, untransformed model
        double aiclog = 0.0;   // AICC, log-transformed model
        bool selected_log = false;
    } trnaic_result;
    // slidingspans{} sfs/chs result (core/src/x11/slidingspans.hpp) -- the
    // Max_%_DIFF column + the derived month-to-month SA-change array; the raw
    // per-span S/Sa/Td arrays live on the real COMMON mirror, sspdat below.
    SlidingSpansOutput ssout;
    HistoryOutput hist_out;
    SpectrumOutput spcout;
    adj_cmn adj;
    adxser_cmn adxser;
    agr_cmn agr;
    agrsrs_cmn agrsrs;
    arima_cmn arima;
    autoq_cmn autoq;
    bstmdl_cmn bstmdl;
    chrt_cmn chrt;
    error_cmn error;
    extend_cmn extend;
    filetb_cmn filetb;
    force_cmn force;
    fxreg_cmn fxreg;
    getarg_cmn getarg;
    global_cmn global;
    goodob_cmn goodob;
    hiddn_cmn hiddn;
    htmlfile_cmn htmlfile;
    htmlout_cmn htmlout;
    inpt_cmn inpt;
    inpt2_cmn inpt2;
    lkhd_cmn lkhd;
    lzero_cmn lzero;
    mdldat_cmn mdldat;
    mdldg_cmn mdldg;
    metadata_cmn metadata;
    missng_cmn missng;
    model_cmn model;
    mq3_cmn mq3;
    newmdl_cmn newmdl;
    orisrs_cmn orisrs;
    otlrev_cmn otlrev;
    otxrev_cmn otxrev;
    picktd_cmn picktd;
    priadj_cmn priadj;
    prior_cmn prior;
    prittl_cmn prittl;
    priusr_cmn priusr;
    rev_cmn rev;
    revsrs_cmn revsrs;
    revtrg_cmn revtrg;
    revusr_cmn revusr;
    rho_cmn rho;
    savcmn_cmn savcmn;
    seatad_cmn seatad;
    seatcm_cmn seatcm;
    seatdg_cmn seatdg;
    seatlg_cmn seatlg;
    seatmd_cmn seatmd;
    seatop_cmn seatop;
    series_cmn series;
    spcidx_cmn spcidx;
    ss2rv_cmn ss2rv;
    ssap_cmn ssap;
    ssft_cmn ssft;
    sspdat_cmn sspdat;
    sspinp_cmn sspinp;
    ssprep_cmn ssprep;
    sspvec_cmn sspvec;
    stcfcm_cmn stcfcm;
    svllog_cmn svllog;
    tbllog_cmn tbllog;
    tdtyp_cmn tdtyp;
    tests_cmn tests;
    tfmts_cmn tfmts;
    title_cmn title;
    tukey_cmn tukey;
    units_cmn units;
    urgbak_cmn urgbak;
    usrreg_cmn usrreg;
    usrxrg_cmn usrxrg;
    work2_cmn work2;
    x11adj_cmn x11adj;
    x11fac_cmn x11fac;
    x11log_cmn x11log;
    x11msc_cmn x11msc;
    x11opt_cmn x11opt;
    x11ptr_cmn x11ptr;
    x11reg_cmn x11reg;
    x11srs_cmn x11srs;
    xclude_cmn xclude;
    xeastr_cmn xeastr;
    xrgfct_cmn xrgfct;
    xrgmdl_cmn xrgmdl;
    xrgum_cmn xrgum;
    xtdtyp_cmn xtdtyp;
    xtrm_cmn xtrm;
};

}  // namespace x13
#endif  // X13_CONTEXT_HPP
