#!/usr/bin/env python
"""prm2hpp -- convert Fortran PARAMETER include files (.prm) to C++ constexpr headers.

Reads every .prm in the source dir, builds a GLOBAL symbol table (parameters may
reference parameters defined in other .prm files, e.g. model.prm uses PSP from
srslen.prm), resolves values by iterated evaluation, and emits one
  <name>.hpp
per input into the output dir, plus an umbrella  all_prm.hpp  that includes them
all. Every constant lands in namespace x13::prm.

Supported PARAMETER types: INTEGER, DOUBLE PRECISION, REAL, LOGICAL,
CHARACTER*n (scalar). Declared-but-not-PARAMETER names (runtime arrays such as
pointer tables) are skipped -- they are variables, not compile-time constants.

Usage:  python prm2hpp.py <fortran_src_dir> <out_dir>
"""
from __future__ import annotations

import os
import re
import sys
from typing import Dict, List, Optional

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fortran_parse import (  # noqa: E402
    logical_statements, strip_trailing_comment, split_top_level, match_paren,
)

HEADER_NOTE = (
    "// Generated by tools/prm2hpp.py from {src}. DO NOT EDIT.\n"
    "// Source of truth: the Fortran PARAMETER include of the same name.\n"
)


class Sym:
    __slots__ = ("name", "ftype", "charlen", "expr", "value", "file")

    def __init__(self, name: str, ftype: str, charlen: Optional[str], expr: str, file: str):
        self.name = name
        self.ftype = ftype          # 'int','double','real','logical','char'
        self.charlen = charlen      # for char: length expr string or None
        self.expr = expr            # raw Fortran RHS
        self.value = None           # resolved Python value
        self.file = file


def canon_type(tok: str) -> str:
    t = tok.strip().upper()
    if t.startswith("DOUBLE"):
        return "double"
    if t.startswith("INTEGER"):
        return "int"
    if t.startswith("REAL"):
        return "real"
    if t.startswith("LOGICAL"):
        return "logical"
    if t.startswith("CHARACTER"):
        return "char"
    return "int"


def parse_type_decls(stmts: List[str]) -> Dict[str, Dict]:
    """Map declared name -> {ftype, charlen}."""
    decls: Dict[str, Dict] = {}
    for s in stmts:
        s = strip_trailing_comment(s).strip()
        u = s.upper()
        m = re.match(r"(DOUBLE\s+PRECISION|INTEGER|REAL|LOGICAL|CHARACTER)\b", u)
        if not m:
            continue
        ftype = canon_type(m.group(1))
        rest = s[m.end():]
        # CHARACTER*n  applies a default length to all names lacking their own *len
        default_len = None
        mm = re.match(r"\s*\*\s*(\d+|\([^)]*\))", rest)
        if ftype == "char" and mm:
            default_len = mm.group(1).strip("()")
            rest = rest[mm.end():]
        # Split the name list at top level.
        for item in split_top_level(rest):
            item = item.strip()
            if not item:
                continue
            # NAME or NAME*len or NAME*(len) or NAME(dims)
            nm = re.match(r"([A-Za-z]\w*)", item)
            if not nm:
                continue
            name = nm.group(1)
            clen = default_len
            lm = re.search(r"\*\s*(\([^)]*\)|\d+)", item)
            if ftype == "char" and lm:
                clen = lm.group(1).strip("()")
            decls[name] = {"ftype": ftype, "charlen": clen}
    return decls


def parse_parameters(stmts: List[str]) -> List[tuple]:
    """Return list of (name, raw_expr) from all PARAMETER statements."""
    params: List[tuple] = []
    for s in stmts:
        s = strip_trailing_comment(s)
        u = s.upper().lstrip()
        if not u.startswith("PARAMETER"):
            continue
        oi = s.find("(")
        if oi < 0:
            continue
        ci = match_paren(s, oi)
        inner = s[oi + 1:ci]
        for assign in split_top_level(inner):
            if "=" not in assign:
                continue
            name, expr = assign.split("=", 1)
            params.append((name.strip(), expr.strip()))
    return params


_REAL_EXP = re.compile(r"(?<![A-Za-z_])(\d+\.?\d*|\.\d+)[dDeE]([+-]?\d+)")


def eval_numeric(expr: str, table: Dict[str, Sym]) -> Optional[float]:
    """Evaluate a Fortran numeric expression using resolved symbols. None if a
    referenced symbol is not yet known."""
    e = expr.strip()
    # Fortran real exponent d/D -> e for Python.
    e = _REAL_EXP.sub(lambda m: m.group(1) + "e" + m.group(2), e)
    # Identifier names, but NOT exponent letters inside a numeric literal (the 'e'
    # in "1e-5" is preceded by a digit, so the lookbehind excludes it).
    names = set(re.findall(r"(?<![\w.])[A-Za-z_]\w*", e))
    env: Dict[str, object] = {}
    for nm in names:
        sym = table.get(nm) or table.get(nm.upper()) or _ci_lookup(table, nm)
        if sym is None or sym.value is None:
            return None
        env[nm] = sym.value
    try:
        return eval(e, {"__builtins__": {}}, env)  # noqa: S307 (trusted vendored input)
    except Exception:
        return None


def _ci_lookup(table: Dict[str, Sym], nm: str) -> Optional[Sym]:
    low = nm.lower()
    for k, v in table.items():
        if k.lower() == low:
            return v
    return None


def eval_logical(expr: str) -> Optional[bool]:
    t = expr.strip().lower()
    if t in (".true.", "t"):
        return True
    if t in (".false.", "f"):
        return False
    return None


def eval_char(expr: str) -> Optional[str]:
    e = expr.strip()
    if not e or e[0] not in "'\"":
        return None
    q = e[0]
    # Strip surrounding quotes, un-double internal quotes.
    body = e[1:]
    if body.endswith(q):
        body = body[:-1]
    return body.replace(q + q, q)


def resolve_all(table: Dict[str, Sym]) -> List[str]:
    """Iteratively resolve symbol values. Returns list of unresolved names."""
    for _ in range(len(table) + 5):
        progressed = False
        for sym in table.values():
            if sym.value is not None:
                continue
            if sym.ftype == "char":
                v = eval_char(sym.expr)
            elif sym.ftype == "logical":
                v = eval_logical(sym.expr)
            else:
                v = eval_numeric(sym.expr, table)
                if v is not None and sym.ftype == "int":
                    v = int(v)  # Fortran integer truncation toward zero
            if v is not None:
                sym.value = v
                progressed = True
        if not progressed:
            break
    return [s.name for s in table.values() if s.value is None]


def cpp_escape(s: str) -> str:
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        else:
            out.append(ch)
    return "".join(out)


def emit_value(sym: Sym) -> str:
    if sym.ftype == "char":
        if sym.charlen in ("1", None) and len(str(sym.value)) == 1:
            return "inline constexpr char {} = '{}';".format(
                sym.name, "\\'" if sym.value == "'" else ("\\\\" if sym.value == "\\" else sym.value))
        return 'inline constexpr std::string_view {} = "{}";'.format(sym.name, cpp_escape(str(sym.value)))
    if sym.ftype == "logical":
        return "inline constexpr bool {} = {};".format(sym.name, "true" if sym.value else "false")
    if sym.ftype == "double":
        return "inline constexpr double {} = {!r};".format(sym.name, float(sym.value))
    if sym.ftype == "real":
        return "inline constexpr float {} = {!r}f;".format(sym.name, float(sym.value))
    return "inline constexpr int {} = {};".format(sym.name, int(sym.value))


def gather_symbols(src_dir: str, exts, table: Optional[Dict[str, Sym]] = None) -> Dict[str, Sym]:
    """Add PARAMETERs from every file with one of `exts` into `table`."""
    if table is None:
        table = {}
    for fn in sorted(f for f in os.listdir(src_dir) if os.path.splitext(f)[1] in exts):
        with open(os.path.join(src_dir, fn), "r", errors="replace") as fh:
            stmts = logical_statements(fh.read())
        decls = parse_type_decls(stmts)
        for name, expr in parse_parameters(stmts):
            if name in table:
                continue  # first definition wins (shared includes are consistent)
            ftype = decls.get(name, {}).get("ftype", "int")
            clen = decls.get(name, {}).get("charlen")
            table[name] = Sym(name, ftype, clen, expr, fn)
    return table


def build_symbol_table(src_dir: str, exts=(".prm", ".i")) -> Dict[str, object]:
    """Resolve PARAMETERs from the given include extensions and return
    {NAME: python value}. Used by cmn2hpp to evaluate COMMON array dimensions."""
    table = gather_symbols(src_dir, exts)
    resolve_all(table)
    return {name: s.value for name, s in table.items() if s.value is not None}


def process(src_dir: str, out_dir: str) -> int:
    prm_files = sorted(f for f in os.listdir(src_dir) if f.endswith(".prm"))
    # Pass 1: gather all declarations + parameters into one global table. A
    # parameter defined in several .prm files (e.g. BRKDSP) is emitted only in the
    # first file that defines it; later duplicates are checked for consistency.
    table: Dict[str, Sym] = {}
    file_params: Dict[str, List[str]] = {}
    skipped: Dict[str, List[str]] = {}
    dup_exprs: Dict[str, List[tuple]] = {}
    for fn in prm_files:
        path = os.path.join(src_dir, fn)
        with open(path, "r", errors="replace") as fh:
            stmts = logical_statements(fh.read())
        decls = parse_type_decls(stmts)
        params = parse_parameters(stmts)
        pnames = []
        for name, expr in params:
            if name in table:
                dup_exprs.setdefault(name, []).append((fn, expr))
                continue  # first-defining file owns the emission
            ftype = decls.get(name, {}).get("ftype", "int")
            clen = decls.get(name, {}).get("charlen")
            table[name] = Sym(name, ftype, clen, expr, fn)
            dup_exprs.setdefault(name, []).append((fn, expr))
            pnames.append(name)
        file_params[fn] = pnames
        # Names declared but never given a PARAMETER value are runtime variables.
        skipped[fn] = [n for n in decls if n not in {p[0] for p in params}]

    unresolved = resolve_all(table)

    # Pass 2: emit one header per file.
    os.makedirs(out_dir, exist_ok=True)
    for fn in prm_files:
        stem = os.path.splitext(fn)[0]
        guard = "X13_PRM_{}_HPP".format(re.sub(r"\W", "_", stem).upper())
        lines = [HEADER_NOTE.format(src="oracle/fortran/" + fn)]
        lines.append("#ifndef {g}\n#define {g}\n".format(g=guard))
        lines.append("#include <string_view>\n")
        lines.append("namespace x13 {\nnamespace prm {\n")
        for name in file_params[fn]:
            sym = table[name]
            if sym.value is None:
                lines.append("// UNRESOLVED: {} = {}".format(name, sym.expr))
            else:
                lines.append(emit_value(sym))
        if skipped[fn]:
            lines.append("// (skipped runtime vars, not PARAMETERs: {})".format(", ".join(sorted(skipped[fn]))))
        lines.append("\n}  // namespace prm\n}  // namespace x13\n")
        lines.append("#endif  // {}\n".format(guard))
        with open(os.path.join(out_dir, stem + ".hpp"), "w") as fh:
            fh.write("\n".join(lines))

    # Umbrella header.
    with open(os.path.join(out_dir, "all_prm.hpp"), "w") as fh:
        fh.write("// Generated by tools/prm2hpp.py. Includes every .prm header. DO NOT EDIT.\n")
        fh.write("#ifndef X13_PRM_ALL_HPP\n#define X13_PRM_ALL_HPP\n")
        for fn in prm_files:
            fh.write('#include "{}.hpp"\n'.format(os.path.splitext(fn)[0]))
        fh.write("#endif  // X13_PRM_ALL_HPP\n")

    resolved = sum(1 for s in table.values() if s.value is not None)
    dups = {n: v for n, v in dup_exprs.items() if len(v) > 1}
    print("prm2hpp: {} files, {} unique parameters, {} resolved, {} unresolved, {} multi-file dups".format(
        len(prm_files), len(table), resolved, len(unresolved), len(dups)))
    if unresolved:
        print("  UNRESOLVED:", ", ".join(sorted(unresolved)))
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(2)
    sys.exit(process(sys.argv[1], sys.argv[2]))
