#!/usr/bin/env python
"""spec_sweep.py -- t-way covering-array sweep of the spec option space.

WHY A COVERING ARRAY
--------------------
The port's failure mode is *silent wrongness*: a spec that both binaries accept
(``OUTCOME: OK``, oracle exits 0) while the numbers differ. Those bugs live at
the seams between features, not inside one feature -- every one found so far was
a two-factor interaction:

  * trading day x the forecast span   (Sprior stopped at Nobspf -> D11 == Inf)
  * holiday regressor x the X-11 calendar combine  (Finhol never defaulted)
  * user prior x the no-model path    (decomposed the raw series)

The full factor space below is ~10^8 combinations, which is untestable. But a
**pairwise (t=2) covering array** hits every (factor_i=level_a, factor_j=level_b)
pair at least once in ~50 rows. That is the whole reduction: it does not test
every combination, it tests every *interaction* of the order that empirically
breaks. Pass ``--t 3`` to cover three-way interactions when a two-way sweep is
clean (costs roughly an order of magnitude more rows).

Rows are generated by greedy randomized search under a validity predicate
(``_valid``), so combinations the oracle rejects outright are never spent.

VERDICTS
--------
  ok          both ran, every compared table agrees within --rtol
  drift       both ran and said OK, numbers differ  <- the bug class hunted here
  engine-err  oracle ran, engine fatalled or crashed (honest gap, or a CRASH)
  oracle-err  the oracle rejects the spec (invalid combination; not a port issue)

Run:  python tools/spec_sweep.py --t 2 --jobs 10
"""
from __future__ import annotations

import argparse
import os
import random
import re
import shutil
import subprocess
from concurrent.futures import ThreadPoolExecutor
from itertools import combinations

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
ORACLE = os.path.join(REPO, "oracle", "fortran", "x13as_ascii_O2.exe")
ENGINE = os.path.join(REPO, "build", "x13run_x11.exe")
DATA = os.path.join(REPO, "tests", "corpus", "data").replace("\\", "/")

TAGS = ["b1", "d10", "d11", "d12", "d13", "d16", "saa", "ffc"]

# Below this magnitude a whole golden column counts as identically zero (see the
# gmax branch in run_case). Well under any real table value, well over the
# roundoff the oracle actually prints for a zero column (~1e-13).
ZERO_COL = 1e-10

# ---------------------------------------------------------------------------
# The factor space. Keep levels to things the oracle accepts on their own; the
# _valid predicate below prunes the invalid *combinations*.
# ---------------------------------------------------------------------------
FACTORS = {
    "series":   ["air", "qtr"],
    "trans":    ["log", "none", "auto"],
    "prior":    ["none", "lom", "lpyear"],
    "reg":      ["none", "td", "td_easter", "easter", "ao", "const", "td_ao"],
    "arima":    ["airline", "ar2", "sar"],
    "outlier":  ["none", "aols", "all"],
    "fcst":     ["one", "two"],
    "bcst":     ["none", "half", "one"],
    "mode":     ["mult", "add", "logadd"],
    "sma":      ["default", "s3x9", "stable", "msr"],
    "tma":      ["default", "9", "23"],
    "sigma":    ["default", "siglim", "calsig"],
    "append":   ["none", "fcst", "bcst", "both"],
    "span":     ["none", "span", "modelspan"],
    "force":    ["none", "denton", "calendaradj", "regress"],
}

REG_VARS = {
    "none": None,
    "td": "td",
    "td_easter": "td easter[8]",
    "easter": "easter[8]",
    "ao": "ao1955.1",
    "const": "const",
    "td_ao": "td ao1955.1",
}


def _valid(row: dict) -> bool:
    """Prune combinations the oracle rejects, so covering rows are not wasted."""
    # regARIMA preadjustment factors require log or no transformation, and a
    # multiplicative/log-additive adjustment requires the log (chkadj.f).
    if row["reg"] != "none" or row["outlier"] != "none":
        if row["mode"] in ("mult", "logadd") and row["trans"] != "log":
            return False
        if row["mode"] == "add" and row["trans"] == "log":
            return False
    # A length-of-period prior cannot be combined with a td/td1coef regressor
    # (gtinpt.f) nor with an additive adjustment (editor.f:751).
    if row["prior"] != "none":
        if "td" in row["reg"]:
            return False
        if row["mode"] != "mult":
            return False
        if row["trans"] != "log":
            return False
    # transform=auto picks the transform, so it cannot be pinned against a mode.
    if row["trans"] == "auto" and row["mode"] != "mult":
        return False
    # The quarterly series has no Easter regressor worth fitting on 4 periods
    # with an 8-day window plus a seasonal AR; keep the pair but not with sar.
    if row["series"] == "qtr" and row["arima"] == "sar" and "easter" in row["reg"]:
        return False
    return True


def spec_text(row: dict) -> str:
    monthly = row["series"] == "air"
    sp = 12 if monthly else 4
    fname = "airline.dat" if monthly else "expgs.dat"
    start = "1949.01" if monthly else "1947.1"

    s = ['title="sweep"', 'file="%s/%s"' % (DATA, fname),
         "start=%s" % start, "period=%d" % sp]
    if row["span"] == "span":
        s.append("span=(1952.01,1959.12)" if monthly else "span=(1952.1,1975.4)")
    elif row["span"] == "modelspan":
        s.append("modelspan=(1950.01,)" if monthly else "modelspan=(1950.1,)")
    s.append("save=(b1)")
    parts = ["series{\n  %s\n}" % "\n  ".join(s)]

    tr = {"log": "function=log", "none": "function=none",
          "auto": "function=auto"}[row["trans"]]
    if row["prior"] != "none":
        tr += " adjust=%s" % ("lom" if monthly else "loq") \
            if row["prior"] == "lom" else " adjust=lpyear"
    parts.append("transform{ %s }" % tr)

    rv = REG_VARS[row["reg"]]
    if rv:
        parts.append("regression{ variables=(%s) }" % rv)

    parts.append({"airline": "arima{ model=(0 1 1)(0 1 1) }",
                  "ar2": "arima{ model=(2 1 0)(0 1 1) }",
                  "sar": "arima{ model=(0 1 1)(1 1 0) }"}[row["arima"]])
    parts.append("estimate{ }")
    if row["outlier"] == "aols":
        parts.append("outlier{ types=(ao ls) }")
    elif row["outlier"] == "all":
        parts.append("outlier{ types=all critical=3.5 }")

    lead = sp if row["fcst"] == "one" else 2 * sp
    fc = "maxlead=%d" % lead
    if row["bcst"] == "half":
        fc += " maxback=%d" % (sp // 2)
    elif row["bcst"] == "one":
        fc += " maxback=%d" % sp
    parts.append("forecast{ %s }" % fc)

    x = ["mode=%s" % row["mode"]]
    if row["sma"] != "default":
        x.append("seasonalma=%s" % row["sma"])
    if row["tma"] != "default":
        x.append("trendma=%s" % row["tma"])
    if row["sigma"] == "siglim":
        x.append("sigmalim=(1.0,2.0)")
    elif row["sigma"] == "calsig":
        x.append("calendarsigma=all")
    if row["append"] in ("fcst", "both"):
        x.append("appendfcst=yes")
    if row["append"] in ("bcst", "both"):
        x.append("appendbcst=yes")
    x.append("save=(d10 d11 d12 d13 d16)")
    parts.append("x11{ %s }" % " ".join(x))

    if row["force"] != "none":
        if row["force"] == "regress":
            parts.append("force{ type=regress target=original rho=0.9 "
                         "save=(saa ffc) }")
        else:
            tgt = "original" if row["force"] == "denton" else "calendaradj"
            parts.append("force{ type=denton target=%s save=(saa ffc) }" % tgt)
    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# Covering-array construction: greedy randomized. While uncovered t-tuples
# remain, sample candidate valid rows and keep the one covering the most.
# ---------------------------------------------------------------------------
def covering_array(t: int, seed: int = 0, candidates: int = 400) -> list[dict]:
    rng = random.Random(seed)
    names = list(FACTORS)

    uncovered = set()
    for combo in combinations(names, t):
        stack = [()]
        for f in combo:
            stack = [p + (v,) for p in stack for v in FACTORS[f]]
        for vals in stack:
            uncovered.add((combo, vals))

    def sample():
        for _ in range(500):
            row = {f: rng.choice(FACTORS[f]) for f in names}
            if _valid(row):
                return row
        return None

    def covers(row):
        got = set()
        for combo in combinations(names, t):
            key = (combo, tuple(row[f] for f in combo))
            if key in uncovered:
                got.add(key)
        return got

    # Drop tuples no valid row can ever contain (they are pruned by _valid).
    reachable = set()
    for _ in range(4000):
        row = sample()
        if row is None:
            break
        for combo in combinations(names, t):
            reachable.add((combo, tuple(row[f] for f in combo)))
    uncovered &= reachable

    rows = []
    while uncovered:
        best, best_got = None, set()
        for _ in range(candidates):
            row = sample()
            if row is None:
                continue
            got = covers(row)
            if len(got) > len(best_got):
                best, best_got = row, got
        if best is None or not best_got:
            break
        rows.append(best)
        uncovered -= best_got
    return rows


ROW_RE = re.compile(r"^(\d{4,6})\s+([+\-][0-9.EeDd+\-]+)")


def _read(path):
    out = {}
    if not os.path.exists(path):
        return out
    with open(path, errors="replace") as f:
        for ln in f:
            m = ROW_RE.match(ln.strip())
            if m:
                out[m.group(1)] = float(m.group(2).replace("D", "E").replace("d", "e"))
    return out


def run_case(item):
    name, row, outdir, rtol = item
    d = os.path.join(outdir, name)
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)
    spc = os.path.join(d, name + ".spc")
    with open(spc, "w", newline="\n") as f:
        f.write(spec_text(row))

    try:
        o = subprocess.run([ORACLE, "-i", name, "-o", name], cwd=d,
                           capture_output=True, text=True, timeout=600)
    except subprocess.TimeoutExpired:
        return name, row, "oracle-timeout", "", 0.0
    otext = o.stdout + o.stderr
    errp = os.path.join(d, name + ".err")
    if os.path.exists(errp):
        otext += open(errp, errors="replace").read()
    if "ERROR" in otext or not os.path.exists(os.path.join(d, name + ".d11")):
        line = next((l.strip() for l in otext.splitlines() if "ERROR" in l), "")
        return name, row, "oracle-err", line[:90], 0.0

    try:
        e = subprocess.run([ENGINE, spc], cwd=d, capture_output=True, text=True,
                           timeout=600)
    except subprocess.TimeoutExpired:
        return name, row, "engine-err", "TIMEOUT", 0.0
    lines = e.stdout.splitlines()
    if e.returncode != 0 or not lines or lines[0].strip() != "OUTCOME: OK":
        crash = "" if 0 <= e.returncode <= 1 else " (rc=%d CRASH)" % e.returncode
        first = next((l.strip() for l in (e.stdout + e.stderr).splitlines()
                      if "ERROR" in l or "not yet ported" in l), "")
        return name, row, "engine-err", (first[:100] + crash) or ("rc=%d" % e.returncode), 0.0

    produced = {t: {} for t in TAGS}
    for ln in lines:
        p = ln.split()
        if len(p) == 3 and p[0] in produced:
            produced[p[0]][p[1]] = float(p[2])

    worst, wtag, wkey, checked = 0.0, "", "", 0
    for t in TAGS:
        g = _read(os.path.join(d, name + "." + t))
        if not g:
            continue
        common = set(g) & set(produced[t])
        if not common:
            return name, row, "no-overlap", t, 0.0
        checked += 1
        # A table whose entire golden column is roundoff dust IS the zero column,
        # and a pointwise relative test against dust is meaningless: with
        # x11{mode=add} the force{} factors are additive DIFFERENCES, so ffc is
        # identically zero -- the oracle prints -1.1e-13, the engine prints an
        # exact 0, and rel comes out 1.000 on a table where both are right.
        # Compare such a column on absolute terms against the same floor.
        gmax = max((abs(v) for v in g.values()), default=0.0)
        if gmax < ZERO_COL:
            for k in common:
                dev = abs(produced[t][k] - g[k])
                if dev >= ZERO_COL and dev > worst:
                    worst, wtag, wkey = dev, t, k
            continue
        for k in common:
            rel = (abs(produced[t][k] - g[k]) / abs(g[k]) if g[k]
                   else abs(produced[t][k] - g[k]))
            if rel > worst:
                worst, wtag, wkey = rel, t, k
    if checked == 0:
        return name, row, "no-tables", "", 0.0
    return name, row, ("ok" if worst <= rtol else "drift"), f"{wtag}@{wkey}", worst


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--t", type=int, default=2, help="interaction strength (2 or 3)")
    ap.add_argument("--jobs", type=int, default=10)
    ap.add_argument("--rtol", type=float, default=1e-8)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--outdir", default=None)
    args = ap.parse_args()

    # abspath: run_case launches both binaries with cwd set to the case dir and
    # hands them the spec path, so a RELATIVE --outdir resolves against the case
    # dir and every engine invocation dies with "cannot open" (rc=2) before doing
    # any work -- which the report then attributes as a 100%-bad CRASH on every
    # level of every factor. If you ever see that, it is the harness, not a port
    # bug: no real defect is uniform across the whole factor space.
    outdir = os.path.abspath(args.outdir or
                             os.path.join(REPO, "build", "spec_sweep"))
    os.makedirs(outdir, exist_ok=True)

    rows = covering_array(args.t, args.seed)
    full = 1
    for v in FACTORS.values():
        full *= len(v)
    print(f"{len(FACTORS)} factors, full factorial {full:,}; "
          f"{args.t}-way covering array = {len(rows)} rows")

    items = [("c%03d" % i, r, outdir, args.rtol) for i, r in enumerate(rows)]
    results = []
    with ThreadPoolExecutor(max_workers=args.jobs) as ex:
        for r in ex.map(run_case, items):
            results.append(r)

    tally = {}
    for _, _, v, _, _ in results:
        tally[v] = tally.get(v, 0) + 1
    print("tally:", tally)

    def show(kind):
        rows_ = [r for r in results if r[2] == kind]
        if not rows_:
            return
        print(f"--- {kind} ({len(rows_)}) ---")
        for name, row, _, detail, worst in rows_:
            sig = " ".join("%s=%s" % (k, v) for k, v in row.items()
                           if v not in ("none", "default"))
            print(f"  {name}  {detail:16s} {worst:.3e}\n      {sig}")

    for kind in ("drift", "no-overlap", "no-tables", "engine-err"):
        show(kind)
    n_or = tally.get("oracle-err", 0)
    if n_or:
        print(f"--- oracle-err ({n_or}) -- invalid combinations, not port issues ---")

    # Factor-level attribution. This is why a covering array is worth building:
    # each level appears in many rows with every other factor varied around it,
    # so a level that is bad shows a high bad/(bad+ok) rate while the levels that
    # merely co-occurred with it wash out. A level at 100% is the culprit.
    print("--- factor-level attribution (bad = drift or crash) ---")
    stats = {}
    for _, row, v, _, _ in results:
        if v in ("oracle-err", "oracle-timeout"):
            continue
        bad = v in ("drift", "no-overlap", "engine-err")
        for f, lv in row.items():
            k = (f, lv)
            a, b = stats.get(k, (0, 0))
            stats[k] = (a + (1 if bad else 0), b + 1)
    ranked = sorted(stats.items(), key=lambda kv: (-(kv[1][0] / kv[1][1]), -kv[1][1]))
    hits = 0
    for (f, lv), (bad, tot) in ranked:
        if bad and bad / tot >= 0.5:
            print(f"  {f:9s} = {lv:12s}  {bad}/{tot} bad ({100*bad/tot:.0f}%)")
            hits += 1
    if not hits:
        print("  (no single level is >=50% bad)")

    # PAIR-level attribution. Single-level attribution is blind to a culprit that
    # is itself an interaction: the appendbcst date-labelling bug needed BOTH
    # bcst!=none AND append in {bcst,both}, so neither factor alone got near 50%
    # and the table above printed nothing at all while seven rows were drifting.
    # Since the whole premise of the covering array is that bugs live at
    # two-factor seams, the attribution has to be able to name a two-factor seam.
    print("--- pair-level attribution ---")
    pstats = {}
    for _, row, v, _, _ in results:
        if v in ("oracle-err", "oracle-timeout"):
            continue
        bad = v in ("drift", "no-overlap", "engine-err")
        items = sorted(row.items())
        for (f1, l1), (f2, l2) in combinations(items, 2):
            k = (f1, l1, f2, l2)
            a, b = pstats.get(k, (0, 0))
            pstats[k] = (a + (1 if bad else 0), b + 1)
    pranked = sorted(pstats.items(),
                     key=lambda kv: (-(kv[1][0] / kv[1][1]), -kv[1][1]))
    shown = 0
    for (f1, l1, f2, l2), (bad, tot) in pranked:
        # Require a real sample: a 1/1 pair is noise, not attribution.
        if bad and bad / tot >= 0.75 and tot >= 3:
            print(f"  {f1}={l1} x {f2}={l2}  {bad}/{tot} bad "
                  f"({100*bad/tot:.0f}%)")
            shown += 1
            if shown >= 15:
                print("  ... (truncated)")
                break
    if not shown:
        print("  (no pair is >=75% bad over >=3 rows)")


if __name__ == "__main__":
    main()
