#!/usr/bin/env python
"""tbltab2hpp -- generate the print/save TABLE tables and their index constants.

prm2hpp.py deliberately skips these: `deftab`, `sumtab` and `level` are Fortran
runtime variables filled by DATA statements, not PARAMETERs, so they live in
`*.var` files it does not read, and it emitted three empty headers saying so.
They are still compile-time constant in every sense that matters -- nothing in
the program ever assigns them -- and the port needs their VALUES to reproduce
gtinpt.f:116-125 and getprt.f:205-208.

Emits one header, `tbltab.hpp`:

  * `x13::prm::DEFTAB[NTBL]`   deftab.var  -- the default print table
  * `x13::prm::SUMTAB[NTBL]`   sumtab.var  -- what `-s` saves
  * `x13::prm::LEVEL[NTBL][NLVL]`  level.var -- print level x table
  * the `L*` table-index constants from the `*tbl*.i` PARAMETER blocks
    (LESTIE, LFORBC, ...), so a reader names its slot instead of a literal.

`tbllog.i` is excluded: its LSP*/NSP* spec-slice constants are already carried,
with their per-spec comments, in `core/src/specparse/specparse.hpp`.

Usage:  python tbltab2hpp.py <fortran_src_dir> <out_dir>
"""
from __future__ import annotations

import os
import re
import sys

HEADER_NOTE = (
    "// Generated by tools/tbltab2hpp.py from oracle/fortran/{{deftab,sumtab,level}}.var\n"
    "// and the *tbl*.i PARAMETER blocks. DO NOT EDIT -- rerun the generator.\n"
)

# The DATA tables. `level` is 2-D: one DATA statement per column.
VAR_FILES = ("deftab", "sumtab", "level")
# Index constants. tbllog.i is owned by specparse.hpp (see the docstring).
IDX_SKIP = {"tbllog.i"}


def code_lines(path: str) -> list[str]:
    """Fortran fixed-form: drop comments, join continuations."""
    out: list[str] = []
    for raw in open(path, encoding="utf-8", errors="replace"):
        line = raw.rstrip("\n")
        if not line.strip():
            continue
        if line[0] in "cC*!":
            continue
        body = line[6:] if len(line) > 6 else ""
        cont = len(line) > 5 and line[5] not in (" ", "0")
        if cont and out:
            out[-1] += body
        else:
            out.append(body)
    return out


def parse_logical_data(path: str, name: str) -> list[list[bool]]:
    """Every `DATA <name>.../ T,F,.../` block, in source order, as bool lists."""
    text = "\n".join(code_lines(path))
    blocks: list[list[bool]] = []
    # DATA sumtab/ ... /   or   DATA(level(i,1),i=1,NTBL)/ ... /
    for m in re.finditer(r"DATA\s*\(?\s*" + name + r"\b[^/]*/(.*?)/", text,
                         re.S | re.I):
        vals = [v.strip() for v in m.group(1).split(",") if v.strip()]
        bad = [v for v in vals if v.upper() not in ("T", "F", ".TRUE.", ".FALSE.")]
        if bad:
            raise SystemExit(f"{path}: {name}: non-logical DATA element(s) {bad[:3]}")
        blocks.append([v.upper() in ("T", ".TRUE.") for v in vals])
    if not blocks:
        raise SystemExit(f"{path}: no DATA block for {name}")
    return blocks


def parse_indices(src: str) -> dict[str, int]:
    """The L<spec><type>=<n> pairs out of every *tbl*.i PARAMETER block."""
    idx: dict[str, int] = {}
    for fn in sorted(os.listdir(src)):
        if not fn.endswith(".i") or "tbl" not in fn or fn in IDX_SKIP:
            continue
        text = "\n".join(code_lines(os.path.join(src, fn)))
        for m in re.finditer(r"PARAMETER\s*\((.*?)\)", text, re.S | re.I):
            for pair in m.group(1).split(","):
                pm = re.match(r"\s*([A-Za-z]\w*)\s*=\s*(\d+)\s*$", pair)
                if not pm:
                    continue
                name, val = pm.group(1).upper(), int(pm.group(2))
                if idx.get(name, val) != val:
                    raise SystemExit(f"{fn}: {name} redefined {idx[name]} -> {val}")
                idx[name] = val
    return idx


def fmt_bools(vals: list[bool], per_line: int = 10, indent: str = "    ") -> str:
    out = []
    for i in range(0, len(vals), per_line):
        chunk = ", ".join("true " if v else "false" for v in vals[i:i + per_line])
        out.append(indent + chunk + ",")
    return "\n".join(out)


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    src, out = sys.argv[1], sys.argv[2]

    deftab = parse_logical_data(os.path.join(src, "deftab.var"), "deftab")[0]
    sumtab = parse_logical_data(os.path.join(src, "sumtab.var"), "sumtab")[0]
    level = parse_logical_data(os.path.join(src, "level.var"), "level")

    ntbl = len(deftab)
    if len(sumtab) != ntbl:
        raise SystemExit(f"sumtab has {len(sumtab)} elements, deftab {ntbl}")
    for i, col in enumerate(level, 1):
        if len(col) != ntbl:
            raise SystemExit(f"level(:,{i}) has {len(col)} elements, expected {ntbl}")
    nlvl = len(level)

    idx = parse_indices(src)

    lines = [HEADER_NOTE.format(), "",
             "#ifndef X13_PRM_TBLTAB_HPP", "#define X13_PRM_TBLTAB_HPP", "",
             "namespace x13 {", "namespace prm {", ""]
    lines.append(f"// deftab.var / sumtab.var / level.var, {ntbl} tables"
                 f" x {nlvl} print levels.")
    lines.append("// 0-BASED here; every reader indexes them with a 1-based L*"
                 " constant minus 1.")
    lines.append(f"inline constexpr int NLVL = {nlvl};")
    lines.append("")
    lines.append("// getprt.f:28's level order: default, none, brief, alltables, all.")
    lines.append(f"inline constexpr bool DEFTAB[{ntbl}] = {{")
    lines.append(fmt_bools(deftab))
    lines.append("};")
    lines.append("")
    lines.append(f"inline constexpr bool SUMTAB[{ntbl}] = {{")
    lines.append(fmt_bools(sumtab))
    lines.append("};")
    lines.append("")
    lines.append(f"inline constexpr bool LEVEL[{ntbl}][{nlvl}] = {{")
    for i in range(ntbl):
        row = ", ".join("true " if level[j][i] else "false" for j in range(nlvl))
        lines.append(f"    {{{row}}},")
    lines.append("};")
    lines.append("")
    lines.append("// Table-index constants (1-based, as in the Fortran).")
    for name in sorted(idx, key=lambda n: (idx[n], n)):
        lines.append(f"inline constexpr int {name} = {idx[name]};")
    lines += ["", "}  // namespace prm", "}  // namespace x13", "",
              "#endif  // X13_PRM_TBLTAB_HPP", ""]

    path = os.path.join(out, "tbltab.hpp")
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {path}: {ntbl} tables, {nlvl} levels, {len(idx)} index constants")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
