# Generated by genextra.py -- DO NOT EDIT BY HAND.
# coverage: identify{} ACF/PACF over diff x sdiff grid
# Regenerate with: python genextra.py
series{
  title = "International Airline Passengers"
  file = "../data/airline.dat"
  start = 1949.01
  period = 12
}
transform{
  function = log
}
identify{
  diff = (0 1)
  sdiff = (0 1)
  maxlag = 36
  print = all
  save = (acf pacf iac ipc)
}
