# Generated by genextra.py -- DO NOT EDIT BY HAND.
# coverage: x11regression{} user prior trading-day weights (tdprior, Kswv=1)
# Regenerate with: python genextra.py
series{
  title = "International Airline Passengers"
  file = "../data/airline.dat"
  start = 1949.01
  period = 12
}
transform{
  function = log
}
arima{
  model = (0 1 1)(0 1 1)
}
estimate{
  print = all
  savelog = all
}
x11{
  print = all
  save = (d10 d11 d12 d13)
  savelog = all
}
x11regression{
  tdprior = (1.4 1.4 1.4 1.4 1.4 0.5 0.5)
  print = all
  save = (a4)
}
