# Generated by genextra.py -- DO NOT EDIT BY HAND.
# coverage: history{} sadj+sadjchng+trend revisions, modest span from 1955
# Regenerate with: python genextra.py
series{
  title = "International Airline Passengers"
  file = "../data/airline.dat"
  start = 1949.01
  period = 12
}
transform{
  function = log
}
arima{
  model = (0 1 1)(0 1 1)
}
estimate{
  print = all
  savelog = all
}
x11{
  print = all
  savelog = all
}
history{
  estimates = (sadj sadjchng trend)
  start = 1955.jan
  print = all
  save = (sar sae chr che trr tre sfr sfe)
  savelog = all
}
