# Generated by genextra.py -- DO NOT EDIT BY HAND.
# coverage: spectrum{} periodogram+AR spectra, sp0/sp1/sp2/spr + Tukey st0/st1/st2, savelog peaks/qs
# Regenerate with: python genextra.py
series{
  title = "International Airline Passengers"
  file = "../data/airline.dat"
  start = 1949.01
  period = 12
}
transform{
  function = log
}
regression{
  variables = (td)
  print = all
}
arima{
  model = (0 1 1)(0 1 1)
}
estimate{
  print = all
  savelog = all
}
forecast{
  maxlead = 12
  print = all
}
x11{
  print = all
  savelog = all
}
spectrum{
  type = periodogram
  print = all
  save = (sp0 sp1 sp2 spr st0 st1 st2)
  savelog = all
}
