# Generated by genextra.py -- DO NOT EDIT BY HAND.
# coverage: transform{file=} permanent user prior factors, no regARIMA model
# Regenerate with: python genextra.py
series{
  title = "International Airline Passengers"
  file = "../data/airline.dat"
  start = 1949.01
  period = 12
}
transform{
  function = log
  file = "prior-strike.dat"
  type = permanent
  mode = percent
  start = 1949.01
}
x11{
  print = all
  save = (d10 d11 d12 d13)
  savelog = all
}
