# Generated by genextra.py -- DO NOT EDIT BY HAND.
# coverage: force{} target=calendaradj (Iftrgt=1 -> Stocal) with regARIMA TD
# Regenerate with: python genextra.py
series{
  title = "International Airline Passengers"
  file = "../data/airline.dat"
  start = 1949.01
  period = 12
}
transform{
  function = log
}
regression{
  variables = (td)
  print = all
}
arima{
  model = (0 1 1)(0 1 1)
}
estimate{
  print = all
  savelog = all
}
x11{
  print = all
  save = (d10 d11 d12 d13)
  savelog = all
}
force{
  type = denton
  target = calendaradj
  print = all
  save = (saa ffc rnd)
}
