# Generated by genextra.py -- DO NOT EDIT BY HAND.
# coverage: force{} regress+round=yes on automdl-x11 -- x11pt3 force gate proof
# Regenerate with: python genextra.py
series{
  title = "International Airline Passengers"
  file = "../data/airline.dat"
  start = 1949.01
  period = 12
}
transform{
  function = auto
}
automdl{
  print = all
  savelog = all
}
forecast{
  maxlead = 12
  print = all
}
x11{
  print = all
  savelog = all
}
force{
  type = regress
  target = original
  round = yes
  rho = 0.9
  print = all
  save = (saa rnd e6a p6a e6r p6r cr rr ffc)
}
