# Generated by genextra.py -- DO NOT EDIT BY HAND.
# coverage: force{} Denton benchmarking of the SA total to original
# Regenerate with: python genextra.py
series{
  title = "International Airline Passengers"
  file = "../data/airline.dat"
  start = 1949.01
  period = 12
}
transform{
  function = log
}
arima{
  model = (0 1 1)(0 1 1)
}
estimate{
  print = all
  savelog = all
}
x11{
  print = all
  savelog = all
}
force{
  type = denton
  target = original
  print = all
  save = (saa ffc rnd)
}
