# Generated by genextra.py -- DO NOT EDIT BY HAND.
# coverage: seats{} tabtables/.tbs + out=2 + HP cycle
# Regenerate with: python genextra.py
series{
  title = "International Airline Passengers"
  file = "../data/airline.dat"
  start = 1949.01
  period = 12
}
transform{
  function = log
}
arima{
  model = (0 1 1)(0 1 1)
}
estimate{
  print = all
  savelog = all
}
forecast{
  maxlead = 12
  print = all
}
seats{
  tabtables = "xo,n,s,p"
  out = 2
  hpcycle = yes
  print = all
  save = (s12 s10 s13 s11 s14 s16 sec tfd sfd ofd afd yfd s18 sta wkf dor dsa dtr cyc ltt)
  savelog = all
}
