# Generated by genextra.py -- DO NOT EDIT BY HAND.
# coverage: spectrum{} AR(30) spectrum + QS check variant
# Regenerate with: python genextra.py
series{
  title = "International Airline Passengers"
  file = "../data/airline.dat"
  start = 1949.01
  period = 12
}
transform{
  function = log
}
arima{
  model = (0 1 1)(0 1 1)
}
estimate{
  print = all
  savelog = all
}
x11{
  print = all
  savelog = all
}
spectrum{
  type = arspec
  maxar = 30
  qcheck = yes
  print = all
  save = (sp0 sp1 sp2 spr st0 st1 st2)
  savelog = all
}
