# Generated by genextra.py -- DO NOT EDIT BY HAND.
# coverage: check{} residual diagnostics with savelog=all
# Regenerate with: python genextra.py
series{
  title = "International Airline Passengers"
  file = "../data/airline.dat"
  start = 1949.01
  period = 12
}
transform{
  function = log
}
arima{
  model = (0 1 1)(0 1 1)
}
estimate{
  print = all
  savelog = all
}
check{
  maxlag = 24
  print = all
  save = (acf pcf ac2)
  savelog = all
}
