# Generated by genextra.py -- DO NOT EDIT BY HAND.
# coverage: outlier{types=all,lsrun} COVID-2020 level shifts on PAYEMS
# Regenerate with: python genextra.py
series{
  title = "US Total Nonfarm Employment (PAYEMS)"
  file = "../data/payems.dat"
  start = 2000.01
  period = 12
}
transform{
  function = log
}
arima{
  model = (0 1 1)(0 1 1)
}
outlier{
  types = all
  lsrun = 3
  critical = 3.5
  print = all
  save = (oit fts)
}
estimate{
  print = all
  savelog = all
}
